<?php
	$url = $this->url('application',['controller'=>'usuario','action'=>'index']);
?>
<h1>Login</h1>

<form action="<?= $url ?>" method="post">
	<div class="form­group">
		<label for="email">Email</label>
		<input type="text" name="email" id="email" class="form­control">
	</div>

	<div class="form­group">
		<label for="senha">Senha</label>
		<input type="password" name="senha" id="senha" class="form­control">
	</div>

</form>

<input type="submit" value="Acessar" class="btn btn­primary">