<?php
$urlEdit = $this->url('application', ['action'=>'editar']);
?>
<h1>Editar Produtos</h1>

<form action="<?= $urlEdit ?>" method="post">
    <div class="form-group">
        <input type="hidden" value="<?= $produto->getId(); ?>" name="id">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" class="form-control" value="<?= $produto->getNome(); ?>">
    </div>
    <div class="form-group">
        <label for="preco">Preço:</label>
        <input type="text" id="preco" name="preco" class="form-control" value="<?= $produto->getPreco(); ?>">
    </div>
    <div class="form-group">
        <label for="descricao">Descrição:</label>
        <textarea name="descricao" id="descricao" class="form-control"><?= $produto->getDescricao(); ?></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary">
    </div>
</form>